config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_scope :user do
  #  authenticated do
      resources :tournaments do
        resources :matches
      end
      resources :scores do
        post "generate_random", to: "scores#generate_random", on: :collection
      end

      if Tournament.where(active: true).any?
        root to: "tournaments#show", id: Tournament.where(active: true).order(created_at: :desc).first.id
      else
        root to: "tournaments#new"
      end
  #  end

    # unauthenticated do
    #   root "devise/sessions#new", as: 'unauthenticated_root'
    # end
  # end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :tournament

  has_many :matches
  has_many :teams
  has_many :scores, through: :matches
  has_many :teams, through: :matches

  validates :group_type, presence: :true
  enum group_type: [
    :a,             # 0
    :b,             # 1
    :play_off_1_4,  # 2
    :play_off_1_2,  # 3
    :final          # 4
  ]
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  belongs_to :group

  has_many :scores
  has_many :teams, through: :scores
end

app/models/score.rb
# frozen_string_literal: true

class Score < ApplicationRecord
  belongs_to :team
  belongs_to :match
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_and_belongs_to_many :tournaments
  belongs_to :group, required: false

  has_many :scores
  has_many :matches, through: :scores

  has_many :tournaments

  validates :title, presence: :true
  validates :off, inclusion: { in: [true, false], message: "Off should be set to true or false" }
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
  include AASM

  has_and_belongs_to_many :teams
  has_many :groups, -> { order(group_type: :asc) }

  accepts_nested_attributes_for :teams, reject_if: proc { |attributes| attributes.values.include?(nil) }, allow_destroy: false, limit: 16
  validates :title, presence: :true
  validate :team

  belongs_to :winner, class_name: "Team", required: false

  TOURNAMENT_STATES = [:no_games, :first_tour, :play_off_1_4, :play_off_1_2, :final, :finished]

  aasm do
    TOURNAMENT_STATES.each_with_index do |state, i|
      if i == 0
        state state, initial: true
      else
        state state
      end
    end
    event :to_next_state do
      transitions from: :final, to: :finished,            after: Proc.new { FinishTournamentService.call(self) }
      transitions from: :play_off_1_2, to: :final,        after: Proc.new { PlayOffService.new.call(self);  }
      transitions from: :play_off_1_4, to: :play_off_1_2, after: Proc.new { PlayOffService.new.call(self);  }
      transitions from: :first_tour, to: :play_off_1_4,   after: Proc.new { ToPlayOffService.new.call(self) }
      transitions from: :no_games, to: :first_tour,       after: Proc.new { FirstTourService.new.call(self) }
    end
  end

  def team
    errors.add(:tournament, "Should have 16 teams involved") if teams.length != 16
    errors.add(:tournament, "All 16 teams should have uniq names") if teams.pluck(:title).uniq.count != teams.pluck(:title).count
  end

  def current_groups
    if aasm_state != TOURNAMENT_STATES[-1].to_s
      aasm_state.in?(["no_games", "first_tour"]) ? groups.limit(2).pluck(:id) : [groups[TOURNAMENT_STATES.index(aasm_state.to_sym)].id]
    else
      [groups.last.id]
    end
  end

  def next_group_id
    groups.where("id > ?", current_groups.last).first.id || groups.last.id
  end

  def has_nil_scores?
    Match.where("group_id IN (?)", current_groups).includes([scores: :team]).where(scores: { score: nil }).any?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :trackable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: :true
  validates :password, presence: :true, length: { minimum: 6 }
end

app/controllers/app_controller.rb
# frozen_string_literal: true

class AppController < ApplicationController; end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:first_name, :last_name, :phone, :email, :password)
      end
    end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < AppController
  # before_action :authenticate_user!
  before_action :set_tournament

  def create
    @tournament.to_next_state! unless @tournament.aasm_state == Tournament::TOURNAMENT_STATES[-1].to_s
    redirect_to tournament_path(@tournament)
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:tournament_id])
  end
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

class ScoresController < AppController
  # before_action :authenticate_user!
  respond_to :js

  def update
    @score = Score.find(params[:id]).update_attributes(score: params[:score])
  end

  def generate_random
    tournament = Tournament.find(params[:tournament_id])
    RandomScoresGenerator.call(tournament)
  end
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < AppController
  # before_action :authenticate_user!
  before_action :set_tournament, only: [:show, :destroy]

  def new
    # Tournament.update_all(active: false)
    DestroyService.call
    Tournament.destroy_all
    @tournament = Tournament.new()
  end

  def show
    @tournament.groups.each do |group|
      self.instance_variable_set("@#{group.group_type}",
                                 Match.where(group_id: group.id).includes([scores: :team])
      )
    end
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.valid?
      @tournament.save
      GroupsGenerator.call(@tournament)
      @tournament.to_next_state!
      redirect_to tournament_path(@tournament), flash: { success: "Teams #{@tournament.teams.map { |t| "'#{t.title}'" }.join(', ')} successfully created!" }
    else
      redirect_to new_tournament_path, flash: { errors: @tournament.errors.messages }
    end
  end

  def destroy; end

  private

    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:title, teams_attributes: [ :id, :title, :off ])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tournaments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="yandex-verification" content="a84d0b3cdd02b5c7" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
    <!-- <div class="m-grid m-grid--hor m-grid--root m-page"> -->
    <%- if !controller._prefixes.include?('devise') %>
      <%= render '/shared/header' %>
      <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
        <%= render '/shared/left_aside' %>
        <div class="m-grid__item m-grid__item--fluid m-wrapper">
          <%= render '/shared/sub_header' %>
          <div class="m-content">
            <%= yield %>
        </div>
      </div>
    <%- elsif controller._prefixes.include?('devise') %>
      <%= yield %>
    <% end %>

  </body>
  <script type="text/javascript">
    var locale = '<%= I18n.locale %>';
  </script>
</html>

app/views/shared/_header.html.haml
/ BEGIN: Header
%header#m_header.m-grid__item.m-header{"m-minimize-mobile-offset" => "200", "m-minimize-offset" => "200"}
  .m-container.m-container--fluid.m-container--full-height
    .m-stack.m-stack--ver.m-stack--desktop
      / BEGIN: Brand
      .m-stack__item.m-brand.m-brand--skin-dark
        .m-stack.m-stack--ver.m-stack--general
          .m-stack__item.m-stack__item--middle.m-brand__logo
            %a.m-brand__logo-wrapper{:href => "index.html"}
              %h4{ style: "color: white !important"} TOURNAMENTS
              -# image_tag "logo/logo_default_dark.png"
          .m-stack__item.m-stack__item--middle.m-brand__tools
            / BEGIN: Left Aside Minimize Toggle
            %a#m_aside_left_minimize_toggle.m-brand__icon.m-brand__toggler.m-brand__toggler--left.m--visible-desktop-inline-block{:href => "javascript:;"}
              %span
            / END
            / BEGIN: Responsive Aside Left Menu Toggler
            %a#m_aside_left_offcanvas_toggle.m-brand__icon.m-brand__toggler.m-brand__toggler--left.m--visible-tablet-and-mobile-inline-block{:href => "javascript:;"}
              %span
            / END
            / BEGIN: Responsive Header Menu Toggler
            %a#m_aside_header_menu_mobile_toggle.m-brand__icon.m-brand__toggler.m--visible-tablet-and-mobile-inline-block{:href => "javascript:;"}
              %span
            / END
            / BEGIN: Topbar Toggler
            %a#m_aside_header_topbar_mobile_toggle.m-brand__icon.m--visible-tablet-and-mobile-inline-block{:href => "javascript:;"}
              %i.flaticon-more
            / BEGIN: Topbar Toggler
      / END: Brand
      #m_header_nav.m-stack__item.m-stack__item--fluid.m-header-head{style: 'background: white'}
        / BEGIN: Horizontal Menu
        %button#m_aside_header_menu_mobile_close_btn.m-aside-header-menu-mobile-close.m-aside-header-menu-mobile-close--skin-dark
          %i.la.la-close
        #m_header_menu.m-header-menu.m-aside-header-menu-mobile.m-aside-header-menu-mobile--offcanvas.m-header-menu--skin-light.m-header-menu--submenu-skin-light.m-aside-header-menu-mobile--skin-dark.m-aside-header-menu-mobile--submenu-skin-dark
          -# if current_user
          %ul.m-menu__nav.m-menu__nav--submenu-arrow
            %li.m-menu__item.m-menu__item--submenu.m-menu__item--rel{"aria-haspopup" => "true", "m-menu-link-redirect" => "1", "m-menu-submenu-toggle" => "click"}
              = link_to new_tournament_path, class: "m-menu__link", data: { confirm: t("tournaments.confirm_new") } do
                %i.m-menu__link-icon.flaticon-add
                %span.m-menu__link-text= t('tournaments.new')
            - unless @tournament.title.nil? || @tournament.aasm_state == Tournament::TOURNAMENT_STATES.last.to_s # || @tournament.aasm_state != Tournament::TOURNAMENT_STATES[-2].to_s
              - if @tournament.has_nil_scores?
                %li.m-menu__item.m-menu__item--submenu.m-menu__item--rel{"aria-haspopup" => "true", "m-menu-link-redirect" => "1", "m-menu-submenu-toggle" => "click"}
                  = link_to "#", onclick: "generate_random_scores('#{@tournament.id}')", class: "m-menu__link tournament_links" do
                    %i.m-menu__link-icon.flaticon-app
                    %span.m-menu__link-text= t('tournaments.generate_score')
              - else
                - unless @tournament.aasm_state == Tournament::TOURNAMENT_STATES[-1].to_s
                  %li.m-menu__item.m-menu__item--submenu.m-menu__item--rel{"aria-haspopup" => "true", "m-menu-link-redirect" => "1", "m-menu-submenu-toggle" => "click"}
                    = form_tag("/tournaments/#{@tournament.id}/matches", method: :post, id: "form_random_scores", style: "display: none") do
                      = submit_tag "To next round", class: "btn btn-primary", style: "visibility: hidden"
                    = link_to "#", onclick: "$('#form_random_scores').submit()", class: "m-menu__link tournament_links" do
                      %i.m-menu__link-icon.flaticon-map
                      %span.m-menu__link-text= @tournament.aasm_state == Tournament::TOURNAMENT_STATES[-2].to_s ? t('tournaments.play_final') : t('tournaments.to_next_round')

        / END: Horizontal Menu
        / BEGIN: Topbar
        #m_header_topbar.m-topbar.m-stack.m-stack--ver.m-stack--general.m-stack--fluid
          .m-stack__item.m-topbar__nav-wrapper
            %ul.m-topbar__nav.m-nav.m-nav--inline
              %li#m_quicksearch.m-nav__item.m-dropdown.m-dropdown--large.m-dropdown--arrow.m-dropdown--align-center.m-dropdown--mobile-full-width.m-dropdown--skin-light.m-list-search.m-list-search--skin-light{"m-dropdown-persistent" => "1", "m-dropdown-toggle" => "click", "m-quicksearch-mode" => "dropdown"}
                %a.m-nav__link.m-dropdown__toggle{:href => "#"}
                .m-dropdown__wrapper
                  %li.m-nav__item.m-topbar__quick-actions.m-topbar__quick-actions--img.m-dropdown.m-dropdown--large.m-dropdown--header-bg-fill.m-dropdown--arrow.m-dropdown--align-right.m-dropdown--align-push.m-dropdown--mobile-full-width.m-dropdown--skin-light{"m-dropdown-toggle" => "click"}
                    -# - if current_user
                    -#   = link_to destroy_user_session_path, method: :delete, class: "m-nav__link" do
                    -#     %span.m-nav__link-badge.m-badge.m-badge--dot.m-badge--info.m--hide
                    -#     %span.m-nav__link-icon
                    -#       %i.flaticon-logout
                    -# - else
                    -#   = link_to new_user_session_path, class: "m-nav__link" do
                    -#     %span.m-nav__link-badge.m-badge.m-badge--dot.m-badge--info.m--hide
                    -#     %span.m-nav__link-icon
                    -#       %i.la.la-sign-in
                  %li.m-nav__item.m-topbar__languages.m-dropdown.m-dropdown--small.m-dropdown--arrow.m-dropdown--align-right.m-dropdown--mobile-full-width{"m-dropdown-toggle" => "click"}
                    %a.m-nav__link.m-dropdown__toggle{:href => "#"}
                      %span.m-nav__link-text
                        = image_tag "flags/013-russia.svg", class: "m-topbar__language-selected-img"
                        -# %img.m-topbar__language-selected-img{:src => "flags/020-flag.svg"}
                      .m-dropdown__wrapper
                        %span.m-dropdown__arrow.m-dropdown__arrow--right.m-dropdown__arrow--adjust
                        .m-dropdown__inner
                          .m-dropdown__header.m--align-center#flagstick_container{ style: 'background: none'}
                            %span.m-dropdown__header-subtitle= t('locales.select_your_language')
                          .m-dropdown__body
                            .m-dropdown__content
                              %ul.m-nav.m-nav--skin-light
                                %li.m-nav__item.m-nav__item--active
                                  = link_to locale: 'en' do
                                    %span.m-nav__link-icon
                                      = image_tag "flags/020-flag.svg", class: "m-topbar__language-img"
                                      -# %img.m-topbar__language-img{:src => "/app/assets/images/flags/020-flag.svg"}/
                                      %span.m-nav__link-title.m-topbar__language-text.m-nav__link-text= t('ls.english')
                                  %li.m-nav__item
                                    = link_to locale: 'ru' do
                                      %span.m-nav__link-icon
                                        = image_tag "flags/013-russia.svg", class: "m-topbar__language-img"
                                        -# %img.m-topbar__language-img{:src => "flags/015-china.svg"}/
                                        %span.m-nav__link-title.m-topbar__language-text.m-nav__link-text= t('ls.russia')
                              - if current_user
                                %li.m-nav__item.m-topbar__user-profile.m-topbar__user-profile--img.m-dropdown.m-dropdown--medium.m-dropdown--arrow.m-dropdown--header-bg-fill.m-dropdown--align-right.m-dropdown--mobile-full-width.m-dropdown--skin-light{"m-dropdown-toggle" => "click"}
                                  %a.m-nav__link.m-dropdown__toggle{:href => "#"}
                                    %span.m-nav__link-icon
                                      %i.flaticon-user
                                  -# %a.m-nav__link.m-dropdown__toggle{:href => "#"}
                                  -#   %span.m-topbar__userpic
                                      -# image_tag "users/user4.jpg", class: "m--img-rounded m--marginless"
                                      -# %img.m--img-rounded.m--marginless{:alt => "", :src => "assets/app/media/img/users/user4.jpg"}/
                                    %span.m-topbar__username.m--hide Nick
                                  .m-dropdown__wrapper
                                    %span.m-dropdown__arrow.m-dropdown__arrow--right.m-dropdown__arrow--adjust
                                    .m-dropdown__inner
                                      .m-dropdown__header.m--align-center#user_profile_container{ style: 'background: transparent'}
                                        - if current_user
                                          .m-card-user.m-card-user--skin-dark
                                            .m-card-user__pic
                                              = image_tag "users/user4.jpg", class: "m--img-rounded m--marginless"
                                              -# %img.m--img-rounded.m--marginless{:alt => "", :src => "assets/app/media/img/users/user4.jpg"}/
                                              /
                                                <span class="m-type m-type--lg m--bg-danger"><span class="m--font-light">S<span><span>
                                            .m-card-user__details
                                              %span.m-card-user__name.m--font-weight-500= "#{current_user.try(:first_name)} #{current_user.try(:last_name)}"
                                              %span.m-card-user__email.m--font-weight-300.m-link= "#{current_user.try(:email)}"
                                        - else
                                      -#     %span
                                      -# .m-dropdown__body
                                      -#   .m-dropdown__content
                                      -#     %ul.m-nav.m-nav--skin-light
                                      -#       %li.m-nav__section.m--hide
                                      -#         %span.m-nav__section-text Section
                                      -#       %li.m-nav__item
                                      -#         = link_to edit_user_registration_path, class: 'm-nav__link' do
                                      -#           %i.m-nav__link-icon.flaticon-profile-1
                                      -#           %span.m-nav__link-title
                                      -#             %span.m-nav__link-wrap
                                      -#               %span.m-nav__link-text My Profile

                        / END: Topbar
                / END: Header

app/views/shared/_left_aside.html.haml
/ BEGIN: Left Aside
%button#m_aside_left_close_btn.m-aside-left-close.m-aside-left-close--skin-dark
  %i.la.la-close
#m_aside_left.m-grid__item.m-aside-left.m-aside-left--skin-dark
  / BEGIN: Aside Menu
  #m_ver_menu.m-aside-menu.m-aside-menu--skin-dark.m-aside-menu--submenu-skin-dark{"m-menu-dropdown-timeout" => "500", "m-menu-scrollable" => "1", "m-menu-vertical" => "1", :style => "position: relative;"}
    %ul.m-menu__nav.m-menu__nav--dropdown-submenu-arrow
      - if current_user
        - [@a, @b, @play_off_1_4, @play_off_1_2, @final].each_with_index do |group, i|
          - if group && group.any?
            %li.m-menu__item
              -#.m-menu__item--active{"aria-haspopup" => "true"}
              %a.m-menu__link{ href: "#table_#{i}"}
                %span.m-menu__link-title
                  %span.m-menu__link-wrap
                    %span.m-menu__link-text= t("group.#{i}")

        .m-grid__item.m-grid__item--fluid.m-wrapper

app/views/shared/_sub_header.html.haml
-# Subheader
.m-subheader
  .d-flex.align-items-center

    %h3.m-subheader__title
      = @tournament.title.nil? ? t('tournaments.create') : @tournament.title
    - if @tournament.aasm_state == Tournament::TOURNAMENT_STATES[-1].to_s && !@tournament.has_nil_scores?
      %h3.m-subheader__title= t('tournaments.winner') + @tournament.winner.title
    %div
      %span#m_dashboard_daterangepicker.m-subheader__daterange
        %span.m-subheader__daterange-label
          %span.m-subheader__daterange-title
          %span.m-subheader__daterange-date.m--font-brand

app/views/tournaments/_form.html.haml
.form-group.m-form__group.has_danger
  = f.text_field :title, class: "form-control m-input", placeholder: t('tournaments.title')
.m-alert.m-alert--outline.alert.alert-info.alert-dismissible.show
  = t("tournaments.help")
.row
  .col-md-4.col-lg-4
    - 8.times do |i|
      -#.m-form__seperator.m-form__seperator--dashed.m-form__seperator--space
      .form-group.m-form__group.row.has_danger
        = text_field_tag :title, "",
                         class: "form-control m-input",
                         name: "[tournament][teams_attributes][#{i + 1}][title]",
                         id: "tournament_teams_attributes_#{i + 1}_title"
        = hidden_field_tag :off, "", value: false, class: "form-control m-input", name: "[tournament][teams_attributes][#{i + 1}][off]"
  .col-md-4.col-lg-4
    - 8.times do |i|
      -#.m-form__seperator.m-form__seperator--dashed.m-form__seperator--space
      .form-group.m-form__group.row.has_danger
        = text_field_tag :title, "",
                         class: "form-control m-input",
                         name: "[tournament][teams_attributes][#{i + 9}][title]",
                         id: "tournament_teams_attributes_#{i + 9}_title"
        = hidden_field_tag :off, "", value: false, class: "form-control m-input", name: "[tournament][teams_attributes][#{i + 9}][off]"

app/views/tournaments/_table.html.haml
.row
  .col-lg-6.col-md-6.col-s-12
    %table#html_table.table-striped.m-table.m-table--head-bg-success{:width => "100%", style: "margin-top: 70px"}
      %thead
        %tr
          %th{style: "text-align: center;", :title => "Team 1 title", colspan: 3}
            %h3= t("group.#{group_index}")

      -# TABLE HEAD

      %thead
        %tr
          %th{ style: "text-align: center;", :title => "Team 1 title"}= t('tournaments.team_1')
          %th{ style: "text-align: center;", :title => "Score"}
            .row
              .col-md-4= t('tournaments.score')
              .col-md-4
              .col-md-4= t('tournaments.score')
          %th{ style: "text-align: center;", :title => "Team 2 title"}= t('tournaments.team_1')

      -# TABLE BODY

      %tbody
        - group.each do |match|
          %tr
            %td{ style: "text-align: center;" }=  match.scores.first.team.title
            %td{ style: "text-align: center;" }
              .row
                .col-md-4
                  %input.form-control.m-input{ style: "text-align: center;", onchange: "set_score('#{match.teams.first.id}', '#{match.id}', this.value)", value: match.scores.first.score, type: 'number', disabled: !match.scores.first.score.nil? }
                .col-md-4
                  %span{ style: "text-align: center" } &mdash;
                .col-md-4
                  %input.form-control.m-input{ style: "text-align: center;", onchange: "set_score('#{match.teams.last.id}', '#{match.id}', this.value)", value: match.scores.last.score, type: 'number', disabled: !match.scores.first.score.nil? }
            %td{ style: "text-align: center;" }= match.scores.second.team.title
    .col-lg-6.col-md-6

app/views/tournaments/new.html.haml
.m-portlet__head
  .m-portlet__head-caption
    .m-portlet__head-title
      %span.m-portlet__head-icon.m--hide
        %i.la.la-gear
= form_for @tournament, validate: true, novalidate: true,
    html: { method: "post", class: "m-form m-form--fit m-form--label-align-right" } do |f|
  .m-portlet__body
    = render 'form', f: f
    .m-form__seperator.m-form__seperator--dashed.m-form__seperator--space

  .m-portlet__foot--fit
    .m-form__actions.m-form__actions
      %button.btn.btn-primary{ type: "submit" }
        = t('tournaments.create')
      = link_to t('cancel'), tournaments_path, class: "btn btn-secondary submit_with_dp"

app/views/tournaments/show.html.haml
.m-portlet__body
  - [@a, @b, @play_off_1_4, @play_off_1_2, @final].each_with_index do |group, i|
    - if group.any?
      %div{ id: "table_#{i}"}
        = render "table", group: group, group_index: i
        %br
        %br

app/views/users/shared/_left_side.html.haml
.m-grid__item
  .m-login__logo
    %a{:href => "#"}
      = image_tag("logo-4.png", :size => "200x200")
.m-grid__item.m-grid__item--fluid.m-grid.m-grid--ver
  .m-grid__item.m-grid__item--middle
    %span.m-login__title
    %span.m-login__subtitle 
.m-grid__item
  .m-login__info
    .m-login__section
      %a.m-link{:href => "#"} &copy 2018 Metronic
    .m-login__section
      %a.m-link{:href => "#"} Privacy
      %a.m-link{:href => "#"} Legal
      %a.m-link{:href => "#"} Contact

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_oauth_links.html.haml
/ begin::Action  ,
.m-login__action
  = link_to new_user_password_path, class: "m-link" do
    %span= t('devise.shared.links.forgot_your_password')
/ end::Action
/ begin::Divider
.m-login__form-divider
  .m-divider
    %span
    %span= t('devise.shared.or')
    %span
/ end::Divider
/ begin::Options
.m-login__options
  %a.btn.btn-primary.m-btn.m-btn--pill.m-btn.m-btn.m-btn--icon{:href => "#"}
    %span
      %i.fab.fa-facebook-f
      %span Facebook
  %a.btn.btn-info.m-btn.m-btn--pill.m-btn.m-btn.m-btn--icon{:href => "#"}
    %span
      %i.fab.fa-twitter
      %span Twitter
  %a.btn.btn-danger.m-btn.m-btn--pill.m-btn.m-btn.m-btn--icon{:href => "#"}
    %span
      %i.fab.fa-google
      %span Google
/ end::Options

app/views/welcome/index.html.haml
<p>Welcome!</p>